site_name: Playing with MKDOCS
theme:
  name: material
  locale: en

nav:
  - Home: "index.md"
  - Drawio: "drawio.md"
  - mermaid: "mermaid.md"
  - Some mathematics: "mathematics.md"

plugins:
  - search
  - drawio_file
  - mermaid2:
      -javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
